"""Reports generated from the database, never hand-maintained.

Everything here is a query. Nothing is a number typed into prose — the same rule
the catalogue side of this repository enforces with `tools/check_docs.py`, for
the same reason: a count written by hand is wrong the first time anyone adds
data.

Reports write Markdown into `warehouse/reports/`, which is tracked and marked
generated in `.gitattributes`.
"""
from __future__ import annotations

import argparse
from datetime import UTC, datetime

from . import config
from .db import DatabaseUnavailable, connect, dicts
from .logging import emit, log

# Columns holding a year, which must never get a thousands separator: "1,990"
# is not a year and reads as a typo.
YEAR_COLUMNS = frozenset({"year", "edition_year", "first_seen", "last_seen",
                          "reference_year", "first_year", "last_year"})


def _table(rows: list[dict], columns: list[tuple[str, str]]) -> str:
    """Render a Markdown table. `columns` is [(key, heading)]."""
    if not rows:
        return "_No rows._\n"
    out = ["| " + " | ".join(h for _, h in columns) + " |",
           "|" + "|".join("---" for _ in columns) + "|"]
    for r in rows:
        cells = []
        for key, _ in columns:
            v = r.get(key)
            if v is None:
                cells.append("")
            elif isinstance(v, int) and not isinstance(v, bool) and key not in YEAR_COLUMNS:
                cells.append(f"{v:,}")
            else:
                cells.append(str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def _write(name: str, title: str, intro: str, sections: list[tuple[str, str]]) -> str:
    config.REPORTS.mkdir(parents=True, exist_ok=True)
    path = config.REPORTS / name
    body = ["<!-- Generated by `atlas-data report`. Do not edit by hand. -->",
            "", f"# {title}", "",
            f"Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')} from the live "
            f"database. Every number here is a query result.", "", intro, ""]
    for heading, content in sections:
        body += [f"## {heading}", "", content, ""]
    path.write_text("\n".join(body), encoding="utf-8")
    return str(path.relative_to(config.ROOT))


def cmd_coverage(args: argparse.Namespace) -> int:
    try:
        with connect() as conn:
            per_edition = dicts(conn, """
                SELECT rel.edition_year AS year, a.parser_family AS family,
                       a.role, a.status,
                       count(DISTINCT sr.record_id)   AS records,
                       count(DISTINCT sr.entity_id)   AS entities,
                       count(fv.field_value_id)       AS raw_values
                  FROM source.artifact a
                  JOIN source.release rel ON rel.release_id = a.release_id
                  LEFT JOIN source.record sr ON sr.artifact_id = a.artifact_id
                  LEFT JOIN source.field_value fv ON fv.record_id = sr.record_id
                 GROUP BY 1,2,3,4 ORDER BY 1,2""")

            loaded = dicts(conn, """
                SELECT rel.edition_year AS year,
                       count(*) FILTER (WHERE o.parse_status <> 'unparsed') AS observations,
                       count(*) FILTER (WHERE o.parse_status = 'unparsed')  AS absences,
                       count(DISTINCT o.entity_id)                          AS entities,
                       count(DISTINCT o.metric_id)                          AS metrics
                  FROM obs.observation o
                  JOIN source.release rel ON rel.release_id = o.release_id
                 GROUP BY 1 ORDER BY 1""")

            totals = dicts(conn, """
                SELECT
                  (SELECT count(*) FROM source.artifact)                    AS artifacts,
                  -- Deliberately by status, not by counting files: the
                  -- superseded 2001 zip is on disk and verified, and is never
                  -- parsed. Labelling this "on disk" would misreport it.
                  (SELECT count(*) FROM source.artifact
                    WHERE status IN ('retrieved','verified'))               AS artifacts_ingestable,
                  (SELECT count(*) FROM source.artifact
                    WHERE status = 'superseded')                            AS artifacts_superseded,
                  (SELECT count(*) FROM source.record)                      AS records,
                  (SELECT count(*) FROM source.field_value)                 AS raw_values,
                  (SELECT count(*) FROM source.field_definition)            AS distinct_fields,
                  (SELECT count(*) FROM core.entity)                        AS entities,
                  (SELECT count(*) FROM obs.observation)                    AS observations,
                  (SELECT count(*) FROM obs.composition_member)             AS composition_members,
                  (SELECT count(*) FROM obs.bilateral_observation)          AS bilateral,
                  (SELECT count(*) FROM geo.entity_point)                   AS points,
                  (SELECT count(*) FROM meta.rejected_record)               AS quarantined
                """)[0]

            intro = "\n".join(
                f"- **{k.replace('_', ' ')}**: {v:,}" for k, v in totals.items())
            path = _write(
                "COVERAGE.md", "Dataset coverage", intro,
                [("Artifacts and staging", _table(per_edition, [
                    ("year", "Edition"), ("family", "Parser family"),
                    ("role", "Role"), ("status", "Status"),
                    ("records", "Records"), ("entities", "Entities"),
                    ("raw_values", "Raw field values")])),
                 ("Canonical load by edition", _table(loaded, [
                     ("year", "Edition"), ("observations", "Observations"),
                     ("absences", "Recorded absences"),
                     ("entities", "Entities"), ("metrics", "Metrics")]))])
            log("info", f"wrote {path}")
            emit(totals)
            return 0
    except DatabaseUnavailable as exc:
        log("error", str(exc))
        return 1


def cmd_fields(args: argparse.Namespace) -> int:
    """The field-evolution report: how a 36-year publication changed its schema."""
    try:
        with connect() as conn:
            rows = dicts(conn, """
                SELECT fd.field_name AS field, fd.section_name AS section,
                       fd.first_seen_year AS first_seen, fd.last_seen_year AS last_seen,
                       fd.edition_count AS editions, fd.record_count AS records,
                       COALESCE(m.code, CASE WHEN fm.target_kind = 'ignore'
                                             THEN '(deliberately unmapped)' END,
                                '') AS metric,
                       left(fd.example_value, 60) AS example
                  FROM source.field_definition fd
                  LEFT JOIN source.field_mapping fm
                         ON fm.dataset_id = fd.dataset_id
                        AND fm.field_pattern = fd.field_name
                        AND fm.status = 'accepted'
                  LEFT JOIN ref.metric m ON m.metric_id = fm.metric_id
                 ORDER BY fd.record_count DESC
                 LIMIT 400""")

            span = dicts(conn, """
                SELECT count(*) AS total,
                       count(*) FILTER (WHERE fm.field_mapping_id IS NOT NULL) AS mapped
                  FROM source.field_definition fd
                  LEFT JOIN source.field_mapping fm
                         ON fm.dataset_id = fd.dataset_id
                        AND fm.field_pattern = fd.field_name
                        AND fm.status = 'accepted'""")[0]

            intro = (
                f"{span['total']:,} distinct section-and-field names occur across the "
                f"corpus; {span['mapped']:,} have an accepted canonical mapping. The "
                f"remainder are fully staged with their raw text preserved and become "
                f"loadable as mappings are added — the gap is the honest measure of "
                f"normalisation coverage, not lost data.\n\n"
                f"The 400 most frequent are listed.")
            path = _write("FIELD-EVOLUTION.md", "Source field evolution", intro,
                          [("Fields by frequency", _table(rows, [
                              ("field", "Field"), ("section", "Section"),
                              ("first_seen", "First"), ("last_seen", "Last"),
                              ("editions", "Editions"), ("records", "Records"),
                              ("metric", "Canonical metric"),
                              ("example", "Example value")]))])
            log("info", f"wrote {path}")
            emit(span)
            return 0
    except DatabaseUnavailable as exc:
        log("error", str(exc))
        return 1


def cmd_storage(args: argparse.Namespace) -> int:
    try:
        with connect() as conn:
            rows = dicts(conn, """
                SELECT n.nspname AS schema, c.relname AS table_name,
                       c.reltuples::bigint AS est_rows,
                       pg_size_pretty(pg_table_size(c.oid))   AS table_size,
                       pg_size_pretty(pg_indexes_size(c.oid)) AS index_size,
                       pg_size_pretty(pg_total_relation_size(c.oid)) AS total_size,
                       pg_total_relation_size(c.oid)          AS total_bytes
                  FROM pg_class c
                  JOIN pg_namespace n ON n.oid = c.relnamespace
                 WHERE c.relkind IN ('r','m')
                   AND n.nspname IN ('meta','source','ref','core','obs','geo','content',
                                     'derived','publication','mart','search','staging_cwf')
                 ORDER BY pg_total_relation_size(c.oid) DESC""")
            total = dicts(conn, "SELECT pg_size_pretty(pg_database_size(current_database())) AS s")[0]
            intro = (f"Total database size: **{total['s']}**. Sizes include indexes and "
                     f"TOAST. `est_rows` is the planner's estimate and is approximate "
                     f"until the table is analysed.")
            path = _write("STORAGE.md", "Database storage", intro,
                          [("Tables and materialised views by total size", _table(rows, [
                              ("schema", "Schema"), ("table_name", "Relation"),
                              ("est_rows", "Est. rows"), ("table_size", "Table"),
                              ("index_size", "Indexes"), ("total_size", "Total")]))])
            log("info", f"wrote {path}")
            emit({"database_size": total["s"], "relations": len(rows)})
            return 0
    except DatabaseUnavailable as exc:
        log("error", str(exc))
        return 1


def cmd_reconcile(args: argparse.Namespace) -> int:
    """Expected versus parsed versus loaded, per edition. §97."""
    try:
        with connect() as conn:
            rows = dicts(conn, """
                SELECT rel.edition_year AS year, a.code AS artifact, a.role,
                       a.parser_family AS family,
                       COALESCE(ir.rows_read, 0)     AS containers_seen,
                       count(DISTINCT sr.record_id)  AS records_parsed,
                       count(DISTINCT sr.entity_id)  AS entities_resolved,
                       count(fv.field_value_id)      AS raw_values,
                       COALESCE(ir.rows_rejected, 0) AS quarantined,
                       -- Observations are keyed to a release, not an artifact:
                       -- 2001 has both a text and an HTML artifact under one
                       -- release. Counting them per artifact would report the
                       -- same observations twice, including against the
                       -- superseded artifact that produced none of them, so the
                       -- column is labelled as a release-level figure.
                       (SELECT count(*) FROM obs.observation o
                         WHERE o.release_id = rel.release_id) AS release_observations
                  FROM source.artifact a
                  JOIN source.release rel ON rel.release_id = a.release_id
                  LEFT JOIN source.record sr ON sr.artifact_id = a.artifact_id
                  LEFT JOIN source.field_value fv ON fv.record_id = sr.record_id
                  LEFT JOIN LATERAL (
                        SELECT rows_read, rows_rejected FROM meta.ingestion_run
                         WHERE artifact_id = a.artifact_id AND stage = 'stage'
                         ORDER BY ingestion_run_id DESC LIMIT 1) ir ON true
                 GROUP BY rel.edition_year, a.code, a.role, a.parser_family,
                          ir.rows_read, ir.rows_rejected, rel.release_id
                 ORDER BY rel.edition_year, a.code""")

            unparsed = [r for r in rows if r["records_parsed"] == 0]
            intro = (
                f"{len(rows)} artifacts. {len(unparsed)} produced no records: each is "
                f"either a deliberately superseded artifact or one whose sub-format has "
                f"no parser yet. A zero here is a statement about coverage and is never "
                f"reported as success.")
            path = _write("RECONCILIATION.md", "Ingestion reconciliation", intro,
                          [("Per artifact", _table(rows, [
                              ("year", "Edition"), ("artifact", "Artifact"),
                              ("role", "Role"), ("family", "Family"),
                              ("containers_seen", "Containers seen"),
                              ("records_parsed", "Records"),
                              ("entities_resolved", "Entities"),
                              ("raw_values", "Raw values"),
                              ("quarantined", "Quarantined"),
                              ("release_observations",
                               "Observations (per release)")]))])
            log("info", f"wrote {path}")
            emit({"artifacts": len(rows), "artifacts_without_records": len(unparsed)})
            return 0
    except DatabaseUnavailable as exc:
        log("error", str(exc))
        return 1
